name: Build APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build_apk:
    name: Build release APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.0'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: xo-dynasty-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
